version: 2

jobs:
  build-and-test:
    docker:
      - image: circleci/node:10.20.1
    steps:
      - checkout
      - run:
          name: Test
          command: ./main.py

workflows:
  main:
    jobs:
      - build-and-test
